name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Get dependencies
      run: make get
    - name: Ensure correct permissions for installer script
      run: chmod a+x packaging/install.sh
    - name: Build & pack application
      run: CURRENT_TAG=${GITHUB_REF/refs\/tags\/v/} make
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        path: "*.tgz"
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: (needs.build.result == 'success')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2.0.10
    - name: List files
      run: tree
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: artifact/myapps.tgz
